url: https://zakelijkaccount.nl
title: Zakelijk Account
logo: /assets/img/header.jpg
slogan: Mijn naam is Sam en ik ben 21 jaar oud! Ik heb een grote passie voor video's maken! Op dit kanaal vind je Nederlandse Gaming video’s
description: Mijn naam is Sam en ik ben 21 jaar oud! Ik heb een grote passie voor video's maken! Op dit kanaal vind je Nederlandse Gaming video’s
show_downloads: true
google_analytics:

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

socials:
  - name: Youtube
    link: https://www.youtube.com/@ZakelijkAccount
    icon: <i class="bi bi-youtube"></i>
    color: btn-danger
  - name: Discord
    link: https://mee6.xyz/i/D11iyaNIgP
    icon: <i class="bi bi-discord"></i>
    color: btn-primary 